# Generated by Django 5.0.1 on 2024-04-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities',
        ),
    ]
