# Generated by Django 5.0.1 on 2024-04-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
