# Generated by Django 5.0.1 on 2024-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=25)),
                ('destination', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('NumTickets', models.IntegerField()),
            ],
        ),
    ]
