# Generated by Django 5.0.1 on 2024-04-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='ticket',
        ),
    ]
