# Generated by Django 5.0.1 on 2024-04-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities',
        ),
    ]
