# Generated by Django 5.0.1 on 2024-04-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
