# Generated by Django 5.0.1 on 2024-04-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='NumTickets',
            new_name='numTickets',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(),
        ),
    ]
