# Generated by Django 5.0.1 on 2024-04-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
