# Generated by Django 5.0.1 on 2024-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_state_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='busid',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
