# Generated by Django 5.0.1 on 2024-04-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_ticket_busid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
    ]
