# Generated by Django 5.0.1 on 2024-04-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_remove_bus_state_delete_ticket_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=25)),
                ('destination', models.CharField(max_length=25)),
                ('numTickets', models.IntegerField()),
                ('busid', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=25)),
                ('busid', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.state')),
            ],
        ),
    ]
