# Generated by Django 5.0.1 on 2024-04-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_ticket_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='busid',
        ),
    ]
