# Generated by Django 5.0.1 on 2024-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
    ]
