# Generated by Django 5.0.1 on 2024-04-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_state_state_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
