# Generated by Django 5.0.1 on 2024-04-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_state_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stateid',
            field=models.IntegerField(default=0),
        ),
    ]
