# Generated by Django 5.0.1 on 2024-04-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_remove_bus_state_delete_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
