# Generated by Django 5.0.1 on 2024-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_state_ticket_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agencyid',
            field=models.IntegerField(default=0),
        ),
    ]
