# Generated by Django 5.0.1 on 2024-04-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_agen_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agen_reg',
        ),
    ]
