# Generated by Django 5.0.1 on 2024-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_bus_agencyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='agencyid',
            field=models.IntegerField(default=0),
        ),
    ]
