# Generated by Django 5.0.1 on 2024-04-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_alter_bus_agencyid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agen_reg',
        ),
    ]
