# Generated by Django 5.0.1 on 2024-04-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
