# Generated by Django 5.0.1 on 2024-04-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_remove_order_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
