# Generated by Django 5.0.1 on 2024-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('busid', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('paymenttype', models.CharField(max_length=10)),
                ('transactionid', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
