# Generated by Django 5.0.1 on 2024-04-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
