# Generated by Django 5.0.1 on 2024-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_remove_order_busid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='orderid',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
